name: "Build"

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt install -y libasound2-dev libmp3lame-dev

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install nasm

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        id: rust

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v${{steps.rust.outputs.cachekey}}-rust

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-file-${{ runner.os }}
          path: target/release/down_on_spot*
          
